'use strict';
// Pure functions: DB rows -> Asterisk config text. No I/O here (unit tested).

const NAME_RE = /^[a-z0-9_]{2,32}$/;
const NUM_RE = /^\+?[0-9]{0,20}$/;
const CODEC_RE = /^[a-z0-9_]+$/;

// Strip anything that could break out of a config line.
const clean = (v) => String(v == null ? '' : v).replace(/[\r\n;#\[\]]/g, '').trim();
const codecs = (s) => String(s || 'ulaw,alaw').split(',').map((c) => c.trim()).filter((c) => CODEC_RE.test(c)).join(',') || 'ulaw,alaw';
const ips = (s) => String(s || '').split(/[\s,]+/).map(clean).filter(Boolean);

// Transport section names in YOUR pjsip.conf. Empty = no transport= line (PJSIP picks a matching one).
const tp = (kind) => {
  const v = (kind === 'tcp' ? process.env.PJSIP_TRANSPORT_TCP : process.env.PJSIP_TRANSPORT_UDP) || '';
  return /^[A-Za-z0-9_.-]+$/.test(v) ? `transport=${v}\n` : '';
};

const HEADER = (what) =>
  `; ${what}\n; GENERATED by SIP Channel Distributor at ${new Date().toISOString()}\n; DO NOT EDIT — changes are overwritten from the web UI.\n\n`;

// DID range "first..last" (same length) -> common prefix + numeric suffix bounds.
const DID_RE = /^[0-9]{4,15}$/;
function didParts(r) {
  const a = String(r.first_did), b = String(r.last_did);
  if (!DID_RE.test(a) || !DID_RE.test(b) || a.length !== b.length || a > b) throw new Error(`invalid DID range ${a}-${b}`);
  let n = 0;
  while (n < a.length && a[n] === b[n]) n++;
  return { len: a.length, prefix: a.slice(0, n), w: a.length - n, lo: +a.slice(n) || 0, hi: +b.slice(n) || 0, count: (+b.slice(n) || 0) - (+a.slice(n) || 0) + 1 };
}
const cliRanges = (t) => (t && t.did_ranges ? t.did_ranges.filter((r) => r.use_as_cli) : []);
// inbound DID routing only when the trunk allows inbound calls
const inRanges = (t) => (t && t.did_ranges && t.allow_inbound !== false ? t.did_ranges : []);

// Working time -> GotoIfTime() check. h = null (any time) or { days: ['mon',..], from: 'HH:MM', to: 'HH:MM' }.
// Jumps to <label> inside working time, otherwise rejects with OFF_HOURS (480). tz = STATS_TZ.
const WDAYS = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];
const TZ_RE = /^[A-Za-z0-9_+\-]+(\/[A-Za-z0-9_+\-]+)*$/;
function timeGate(h, label, tz) {
  if (!h) return '';
  const days = WDAYS.filter((d) => (h.days || []).includes(d));
  const hm = /^([01][0-9]|2[0-3]):[0-5][0-9]$/;
  if (!days.length || !hm.test(h.from) || !hm.test(h.to)) throw new Error(`invalid working time ${JSON.stringify(h)}`);
  const zone = tz && TZ_RE.test(tz) ? `,${tz}` : '';
  return ` same => n,GotoIfTime(${h.from}-${h.to},${days.length === 7 ? '*' : days.join('&')},*,*${zone}?${label})
` +
    hangup('OFF_HOURS') +
    ` same => n(${label}),NoOp(working time ${h.from}-${h.to} ${days.join(',')})
`;
}
// SIP response the customer gets for each distributor reject (editable on the Dispositions page) -> Q.850 cause for
// Hangup(); chan_pjsip turns the cause back into that SIP code.
const SIP_CAUSE = { 403: 21, 404: 1, 408: 18, 480: 20, 484: 28, 486: 17, 488: 58, 500: 38, 502: 27, 503: 34 };
const DEFAULT_REJECT = { CHANNEL_LIMIT: 503, TRUNK_LIMIT: 503, BLOCKED: 403, NO_ROUTE: 503, INVALID: 404,
  OFF_HOURS: 480, NO_HEADER: 484, INVALID_DID: 403 };
let rejectSip = DEFAULT_REJECT;   // set by renderDialplan() for the duration of one (synchronous) render
const cause = (disp) => SIP_CAUSE[rejectSip[disp]] || SIP_CAUSE[DEFAULT_REJECT[disp]];
const hangup = (disp, label) => ` same => n${label ? `(${label})` : ''},Set(SD_DISP=${disp})\n same => n,Hangup(${cause(disp)})\n`;

const hoursOf = (v) => (typeof v === 'string' ? JSON.parse(v) : v) || null;

function assertName(n, kind) {
  if (!NAME_RE.test(n)) throw new Error(`invalid ${kind} name "${n}"`);
}

// ---------------------------------------------------------------- trunks.conf
function renderTrunks(trunks) {
  let out = HEADER('Carrier SIP trunks (pjsip)');
  for (const t of trunks.filter((x) => x.active)) {
    assertName(t.name, 'trunk');
    const id = `t_${t.name}`;
    const host = clean(t.host);
    const port = +t.port || 5060;
    const transport = tp(t.transport === 'tcp' ? 'tcp' : 'udp');
    const hasAuth = !!(t.username && t.password);

    out += `;; ---- trunk ${t.name}${t.description ? ' — ' + clean(t.description) : ''} (max ${t.max_channels || 'unlimited'} ch)\n`;
    out += `[${id}]\ntype=aor\ncontact=sip:${host}:${port}\nqualify_frequency=60\nqualify_timeout=3\n\n`;
    if (hasAuth) {
      out += `[${id}-auth]\ntype=auth\nauth_type=userpass\nusername=${clean(t.username)}\npassword=${clean(t.password)}\n\n`;
    }
    // trunks allowing inbound with DID ranges accept calls (sd-in-<name>), all others reject them
    const ctx = inRanges(t).length ? `sd-in-${t.name}` : 'sd-from-trunk';
    out += `[${id}]\ntype=endpoint\n${transport}context=${ctx}\n` +
      `disallow=all\nallow=${codecs(t.codecs)}\naors=${id}\n` +
      (hasAuth ? `outbound_auth=${id}-auth\n` : '') +
      (t.from_user ? `from_user=${clean(t.from_user)}\n` : '') +
      (t.from_domain ? `from_domain=${clean(t.from_domain)}\n` : '') +
      `direct_media=no\nrtp_symmetric=yes\nforce_rport=yes\nrewrite_contact=yes\n` +
      `send_rpid=yes\ntrust_id_outbound=yes\ntimers=no\n\n`;
    out += `[${id}-identify]\ntype=identify\nendpoint=${id}\nmatch=${host}\n\n`;
    if (t.register && hasAuth) {
      out += `[${id}-reg]\ntype=registration\n${transport}outbound_auth=${id}-auth\n` +
        `server_uri=sip:${host}:${port}\nclient_uri=sip:${clean(t.username)}@${host}:${port}\n` +
        `contact_user=${clean(t.username)}\nretry_interval=30\nforbidden_retry_interval=300\n` +
        `fatal_retry_interval=300\nexpiration=3600\nline=yes\nendpoint=${id}\n\n`;
    }
  }
  return out;
}

// ------------------------------------------------------------- processes.conf
function renderProcesses(processes) {
  let out = HEADER('Customer Asterisk servers = processes (pjsip)');
  for (const p of processes) {
    assertName(p.code, 'process');
    const id = `p_${p.code}`;
    const byIp = p.auth_type === 'ip';
    out += `;; ---- process ${p.code} — ${clean(p.name)} (limit ${p.channel_limit} ch)${p.active ? '' : ' [INACTIVE]'}\n`;
    // AOR = where inbound DID calls are sent: the customer's first fixed IP, or its registration
    const fixedIp = byIp ? ips(p.allowed_ips).find((i) => !i.includes('/')) : null;
    if (byIp && fixedIp) out += `[${id}]\ntype=aor\ncontact=sip:${fixedIp}:5060\n\n`;
    else if (!byIp) out += `[${id}]\ntype=aor\nmax_contacts=1\nremove_existing=yes\n\n`;
    const aor = !byIp || fixedIp ? `aors=${id}\n` : '';
    out += `[${id}]\ntype=endpoint\n${tp('udp')}context=proc-${p.code}\n${aor}` +
      `disallow=all\nallow=${codecs(p.codecs)}\n` +
      `direct_media=no\nrtp_symmetric=yes\nforce_rport=yes\nrewrite_contact=yes\n` +
      `trust_id_inbound=yes\ntimers=no\nallow_subscribe=no\n` +
      (byIp ? `identify_by=ip\n` : `identify_by=auth_username,username\nauth=${id}-auth\n`) + '\n';
    if (byIp) {
      const list = ips(p.allowed_ips);
      if (list.length) {
        out += `[${id}-identify]\ntype=identify\nendpoint=${id}\n` + list.map((i) => `match=${i}\n`).join('') + '\n';
      } else {
        out += `; WARNING: no allowed IPs set — this process cannot be identified\n\n`;
      }
    } else {
      out += `[${id}-auth]\ntype=auth\nauth_type=userpass\nusername=${clean(p.sip_username)}\npassword=${clean(p.sip_password)}\n\n`;
    }
  }
  return out;
}

// -------------------------------------------------------------- dialplan.conf
// Channel limit enforcement = join group, THEN count. Two calls arriving together both
// see the higher count, so the limit can never be overshot (worst case: both rejected).
function hangupHandler() {
  return `[sd-hangup]
; Runs on every customer channel at hangup -> UserEvent -> ARI -> Node writes calls + daily_stats
exten => s,1,ExecIf($["\${SD_DISP}" = ""]?Set(SD_DISP=\${IF($["\${DIALSTATUS}" = ""]?FAILED:\${DIALSTATUS})}))
 same => n,UserEvent(SIPDIST_END,proc: \${SD_PROC},trunk: \${SD_TRUNK},num: \${SD_NUM},out: \${SD_OUT},cli: \${SD_CLI},cliout: \${SD_CLIOUT},disp: \${SD_DISP},dialstatus: \${DIALSTATUS},cause: \${HANGUPCAUSE},start: \${SD_START},end: \${EPOCH},bill: \${ANSWEREDTIME},dialed: \${DIALEDTIME},uid: \${UNIQUEID},linked: \${CHANNEL(linkedid)},src: \${SD_SRC},dir: \${SD_DIR},did: \${SD_DIDUSED},hst: \${SD_HST},hdid: \${SD_HDID:0:40},hnum: \${SD_HNUM:0:40})
 same => n,Return()

[sd-inhdr]
; pre-dial on the leg to the process (inbound DID calls): ARG1 = DID, ARG2 = caller's number
exten => s,1,Set(PJSIP_HEADER(add,X-DID)=\${ARG1})
 same => n,Set(PJSIP_HEADER(add,X-Number)=\${ARG2})
 same => n,Return()

[sd-from-trunk]
; Carriers may not send calls in — reject
exten => _.,1,Hangup(21)
exten => h,1,Hangup()   ; explicit h that ends execution: with only "_." Asterisk would run the reject code at hangup

`;
}

const ENTRY = (code, trunkName) =>
  ` same => n,Set(SD_START=\${EPOCH})\n` +
  ` same => n,Set(SD_PROC=${code})\n` +
  ` same => n,Set(SD_TRUNK=${trunkName || ''})\n` +
  ` same => n,Set(SD_NUM=\${EXTEN})\n` +
  ` same => n,Set(SD_CLI=\${CALLERID(num)})\n` +
  ` same => n,Set(SD_SRC=\${CHANNEL(pjsip,remote_addr)})\n` +
  ` same => n,Set(CHANNEL(hangup_handler_push)=sd-hangup,s,1)\n`;

function reject(code, trunkName, disp, comment) {
  return `exten => _.,1,NoOp(${comment} -> ${rejectSip[disp]})\n` + ENTRY(code, trunkName) + hangup(disp);
}

// limits -> number -> caller ID -> Dial -> limit labels. num = dialplan expression of the number to send,
// cliLines = dialplan lines that set CALLERID before dialing.
function dialTail(p, t, num, cliLines) {
  const prefix = NUM_RE.test(t.prefix || '') ? (t.prefix || '') : '';
  const strip = Math.max(0, Math.min(10, +t.strip_digits || 0));
  const tmax = +t.max_channels || 0;
  const timeout = Math.max(5, Math.min(300, +t.dial_timeout || 60));
  return ` same => n,Set(GROUP(sdproc)=${p.code})\n` +
    ` same => n,GotoIf($[\${GROUP_COUNT(${p.code}@sdproc)} > ${+p.channel_limit}]?plimit)\n` +
    (tmax > 0
      ? ` same => n,Set(GROUP(sdtrunk)=${t.name})\n` +
        ` same => n,GotoIf($[\${GROUP_COUNT(${t.name}@sdtrunk)} > ${tmax}]?tlimit)\n`
      : '') +
    ` same => n,Set(SD_OUT=${prefix}\${${num}:${strip}})\n` +
    cliLines +
    ` same => n,Set(SD_CLIOUT=\${CALLERID(num)})\n` +
    ` same => n,Dial(PJSIP/\${SD_OUT}@t_${t.name},${timeout})\n` +
    ` same => n,Hangup()\n` +
    hangup('CHANNEL_LIMIT', 'plimit') +
    (tmax > 0 ? hangup('TRUNK_LIMIT', 'tlimit') : '');
}

// Outbound = header dialing only: the client (identified by IP) dials the process's dummy number and sends
// X-DID (caller ID, must be a caller-ID DID of the trunk) + X-Number (customer number), digits with an optional
// leading +. Missing/bad header -> NO_HEADER, DID off-trunk -> INVALID_DID, any other dialed number -> INVALID.
const DUMMY_RE = /^[0-9]{4,20}$/;
const HDR_DID = 'X-DID';
const HDR_NUM = 'X-Number';
const SAFE = '0-9a-zA-Z+.';   // raw header values are reduced to these chars before logging
function headerCheck(t) {
  return ` same => n,Set(SD_HDIDL=\${LEN(\${PJSIP_HEADER(read,${HDR_DID})})})\n` +
    ` same => n,Set(SD_HNUML=\${LEN(\${PJSIP_HEADER(read,${HDR_NUM})})})\n` +
    ` same => n,Set(SD_HDID=\${FILTER(${SAFE},\${PJSIP_HEADER(read,${HDR_DID})})})\n` +
    ` same => n,Set(SD_HNUM=\${FILTER(${SAFE},\${PJSIP_HEADER(read,${HDR_NUM})})})\n` +
    ` same => n,Set(SD_DID=\${FILTER(0-9,\${SD_HDID})})\n` +
    ` same => n,Set(SD_CNUM=\${FILTER(0-9,\${SD_HNUM})})\n` +
    ` same => n,Set(SD_HST=missing)\n` +
    ` same => n,GotoIf($[\${SD_HDIDL} = 0 | \${SD_HNUML} = 0]?nohdr)\n` +
    // raw length vs. length of the digits/+ part: any other character makes the header invalid (no silent cleanup)
    ` same => n,Set(SD_HST=bad_number)\n` +
    ` same => n,GotoIf($[\${LEN(\${FILTER(0-9+,\${SD_HNUM})})} != \${SD_HNUML}]?nohdr)\n` +
    ` same => n,GotoIf($[\${LEN(\${SD_CNUM})} < 4 | \${LEN(\${SD_CNUM})} > 20]?nohdr)\n` +
    ` same => n,Set(SD_HST=bad_did)\n` +
    ` same => n,GotoIf($[\${LEN(\${FILTER(0-9+,\${SD_HDID})})} != \${SD_HDIDL}]?baddid)\n` +
    (cliRanges(t).length ? ` same => n,Gosub(sd-didok-${t.name},s,1)\n` : ` same => n,Set(SD_DIDOK=0)\n`) +
    ` same => n,GotoIf($[\${SD_DIDOK} != 1]?baddid)\n` +
    ` same => n,Set(SD_HST=ok)\n same => n,Set(SD_NUM=\${SD_CNUM})\n same => n,Set(SD_DIDUSED=\${SD_DID})\n` +
    ` same => n,Set(SD_DEST=\${SD_CNUM})\n same => n,Set(CALLERID(all)=\${SD_DID} <\${SD_DID}>)\n`;
}
const headerRejects = () => hangup('NO_HEADER', 'nohdr') + hangup('INVALID_DID', 'baddid');

// [sd-didok-<trunk>]: SD_DIDOK=1 when SD_DID (digits only) is inside one of the trunk's caller-ID ranges
function didCheckContext(t) {
  let out = `[sd-didok-${t.name}]\nexten => s,1,Set(SD_DIDOK=0)\n`;
  for (const d of cliRanges(t).map(didParts)) {
    const cond = [`\${LEN(\${SD_DID})} = ${d.len}`];
    if (d.prefix) cond.push(`"\${SD_DID:0:${d.prefix.length}}" = "${d.prefix}"`);
    if (d.w) cond.push(`\${SD_DID:${d.prefix.length}} >= ${d.lo}`, `\${SD_DID:${d.prefix.length}} <= ${d.hi}`);
    out += ` same => n,GotoIf($[${cond.join(' & ')}]?ok)\n`;
  }
  return out + ` same => n,Return()\n same => n(ok),Set(SD_DIDOK=1)\n same => n,Return()\n\n`;
}

// rejectCodes: { CHANNEL_LIMIT: 486, ... } SIP response per distributor disposition (missing = default)
function renderDialplan(processes, trunks, tz, routeUrl, rejectCodes) {
  rejectSip = { ...DEFAULT_REJECT };
  for (const [d, c] of Object.entries(rejectCodes || {})) if (d in DEFAULT_REJECT && SIP_CAUSE[c]) rejectSip[d] = +c;
  const byId = new Map(trunks.map((t) => [t.id, t]));
  let out = HEADER('Process contexts (dialplan)') + hangupHandler();

  for (const p of processes) {
    assertName(p.code, 'process');
    const t = p.trunk_id ? byId.get(p.trunk_id) : null;
    // explicit h ending in Hangup(): otherwise the catch-all '_.' below runs at hangup (h,1 or falling through to h,2)
    // and overwrites SD_DISP with INVALID
    out += `[proc-${p.code}]\n; ${clean(p.name)} — limit ${p.channel_limit}, trunk ${t ? t.name : '(none)'}\nexten => h,1,Hangup()\n`;

    if (!p.active) { out += reject(p.code, t && t.name, 'BLOCKED', 'process inactive') + '\n'; continue; }
    if (p.allow_outbound === false) { out += reject(p.code, t && t.name, 'BLOCKED', 'outbound calls disabled') + '\n'; continue; }
    if (!t || !t.active) { out += reject(p.code, t && t.name, 'NO_ROUTE', 'no active trunk') + '\n'; continue; }

    assertName(t.name, 'trunk');
    const dummy = String(p.dummy_cli || '');
    if (DUMMY_RE.test(dummy)) {
      out += `exten => ${dummy},1,NoOp(${p.code} dummy number -> X-Number via ${t.name}, caller ID = X-DID)\n` + ENTRY(p.code, t.name) +
        headerCheck(t) +
        timeGate(hoursOf(p.out_hours), 'open', tz) +
        dialTail(p, t, 'SD_DEST', '') +
        headerRejects();
    } else {
      out += `; WARNING: no valid dummy number - every call is rejected\n`;
    }
    out += reject(p.code, t.name, 'INVALID', 'dialed number is not the dummy number') + '\n';
  }
  for (const t of trunks.filter((x) => x.active)) {
    assertName(t.name, 'trunk');
    if (cliRanges(t).length) out += didCliContext(t) + didCheckContext(t);
    if (inRanges(t).length) out += inboundContext(t, processes, tz, routeUrl);
  }
  return out;
}

// [sd-cli-<trunk>]: SD_DIDCLI = random DID from the trunk's caller-ID ranges (weighted by range size)
function didCliContext(t) {
  const parts = cliRanges(t).map(didParts);
  const total = parts.reduce((s, r) => s + r.count, 0);
  let out = `[sd-cli-${t.name}]\nexten => s,1,Set(LOCAL(sdr)=\${RAND(1,${total})})\n`;
  let cum = 0;
  parts.forEach((r, i) => { cum += r.count; out += ` same => n,GotoIf($[\${sdr} <= ${cum}]?r${i})\n`; });
  parts.forEach((r, i) => {
    out += r.w
      ? ` same => n(r${i}),Set(LOCAL(sdx)=${'0'.repeat(r.w)}\${RAND(${r.lo},${r.hi})})\n same => n,Set(SD_DIDCLI=${r.prefix}\${sdx:-${r.w}})\n same => n,Return()\n`
      : ` same => n(r${i}),Set(SD_DIDCLI=${r.prefix})\n same => n,Return()\n`;
  });
  return out + '\n';
}

// [sd-in-<trunk>]: carrier calls a DID -> DID must be in one of the trunk's ranges -> pick the process:
//   1. ask the app (routeUrl): process that last called this caller with this DID as caller ID, else the last
//      process that used the DID as caller ID   2. else the process the range is assigned to   3. else NO_ROUTE.
// The call goes to the process's fixed IP: dialed number = the caller's (customer) number, caller ID = the DID,
// plus headers X-DID / X-Number.
function inboundContext(t, processes, tz, routeUrl) {
  const byId = new Map(processes.map((p) => [p.id, p]));
  const lim = +t.max_channels || 0;
  const timeout = Math.max(5, Math.min(300, +t.dial_timeout || 60));
  let out = `[sd-in-${t.name}]\n; inbound DIDs on trunk ${t.name}\nexten => h,1,Hangup()\n` +
    `exten => _[+0-9].,1,NoOp(inbound DID on ${t.name})\n` +
    ` same => n,Set(SD_DIR=in)\n same => n,Set(SD_START=\${EPOCH})\n same => n,Set(SD_TRUNK=${t.name})\n` +
    ` same => n,Set(SD_NUM=\${EXTEN})\n same => n,Set(SD_CLI=\${CALLERID(num)})\n same => n,Set(SD_SRC=\${CHANNEL(pjsip,remote_addr)})\n` +
    ` same => n,Set(CHANNEL(hangup_handler_push)=sd-hangup,s,1)\n` +
    ` same => n,Set(SD_DID=\${FILTER(0-9,\${EXTEN})})\n`;
  const ranges = inRanges(t).map((r) => ({ r, d: didParts(r), p: r.process_id ? byId.get(r.process_id) : null }));
  ranges.forEach(({ d }, i) => {   // match on the last N digits (carrier may add a country code)
    const cond = [`\${LEN(\${SD_DID})} >= ${d.len}`];
    if (d.prefix) cond.push(`"\${SD_DID:-${d.len}:${d.prefix.length}}" = "${d.prefix}"`);
    if (d.w) cond.push(`\${SD_DID:-${d.w}} >= ${d.lo}`, `\${SD_DID:-${d.w}} <= ${d.hi}`);
    out += ` same => n,GotoIf($[${cond.join(' & ')}]?r${i})\n`;
  });
  out += hangup('INVALID');
  ranges.forEach(({ d, p }, i) => {
    if (p) assertName(p.code, 'process');
    out += ` same => n(r${i}),Set(SD_DIDM=\${SD_DID:-${d.len}})\n same => n,Set(SD_ASG=${p ? p.code : ''})\n same => n,Goto(found)\n`;
  });
  out += ` same => n(found),Set(SD_CUST=\${FILTER(0-9,\${CALLERID(num)})})\n same => n,Set(SD_DIDUSED=\${SD_DIDM})\n` +
    ` same => n,Set(SD_INPROC=)\n` +
    (routeUrl
      ? ` same => n,Set(CURLOPT(conntimeout)=1)\n same => n,Set(CURLOPT(httptimeout)=2)\n` +
        ` same => n,Set(SD_INPROC=\${FILTER(a-z0-9_,\${CURL(${routeUrl}?did=\${SD_DIDM}&from=\${SD_CUST})})})\n`
      : '') +
    ` same => n,ExecIf($["\${SD_INPROC}" = ""]?Set(SD_INPROC=\${SD_ASG}))\n` +
    ` same => n,NoOp(DID \${SD_DIDM} from \${SD_CUST} -> process \${SD_INPROC})\n`;
  for (const p of processes) { assertName(p.code, 'process'); out += ` same => n,GotoIf($["\${SD_INPROC}" = "${p.code}"]?in_${p.code})\n`; }
  out += hangup('NO_ROUTE');
  for (const p of processes) {
    out += ` same => n(in_${p.code}),Set(SD_PROC=${p.code})\n`;
    const byIp = p.auth_type === 'ip';
    if (!p.active || p.allow_inbound === false) {
      out += ` same => n,NoOp(${p.active ? 'inbound calls disabled' : 'process inactive'})\n` + hangup('BLOCKED');
      continue;
    }
    if (byIp && !ips(p.allowed_ips).some((i) => !i.includes('/'))) {
      out += ` same => n,NoOp(process ${p.code} has no fixed IP to send calls to)\n` + hangup('NO_ROUTE');
      continue;
    }
    out += timeGate(hoursOf(p.in_hours), `in_${p.code}_open`, tz) +
      ` same => n,Set(GROUP(sdproc)=${p.code})\n` +
      ` same => n,GotoIf($[\${GROUP_COUNT(${p.code}@sdproc)} > ${+p.channel_limit}]?plimit)\n` +
      (lim > 0 ? ` same => n,Set(GROUP(sdtrunk)=${t.name})\n same => n,GotoIf($[\${GROUP_COUNT(${t.name}@sdtrunk)} > ${lim}]?tlimit)\n` : '') +
      ` same => n,Set(SD_OUT=\${IF($["\${SD_CUST}" = ""]?\${SD_DIDM}:\${SD_CUST})})\n` +
      ` same => n,Set(CALLERID(all)=\${SD_DIDM} <\${SD_DIDM}>)\n` +
      ` same => n,Set(SD_CLIOUT=\${SD_DIDM})\n` +
      ` same => n,Dial(PJSIP/\${SD_OUT}@p_${p.code},${timeout},b(sd-inhdr^s^1(\${SD_DIDM},\${SD_CUST})))\n same => n,Hangup()\n`;
  }
  out += hangup('CHANNEL_LIMIT', 'plimit') + hangup('TRUNK_LIMIT', 'tlimit') + '\n';
  return out;
}

// ------------------------------------------------- config for the customer side
function peerConfig(p, publicIp, sipPort = 5060, dids = []) {
  const ip = clean(publicIp);
  const hdr = { did: HDR_DID, nn: HDR_NUM };
  const dummy = DUMMY_RE.test(String(p.dummy_cli || '')) ? p.dummy_cli : '<dummy number>';
  const byIp = p.auth_type === 'ip';
  const user = clean(p.sip_username);
  const pass = clean(p.sip_password);
  const pj =
`; ===== PJSIP (pjsip.conf) on the customer Asterisk "${clean(p.name)}" =====
[sipdist]
type=aor
contact=sip:${ip}:${sipPort}
qualify_frequency=60
${byIp ? '' : `
[sipdist-auth]
type=auth
auth_type=userpass
username=${user}
password=${pass}
`}
[sipdist]
type=endpoint
context=from-sipdist
disallow=all
allow=ulaw,alaw
aors=sipdist
direct_media=no
${byIp ? '' : `outbound_auth=sipdist-auth\nfrom_user=${user}\n`}
[sipdist-identify]
type=identify
endpoint=sipdist
match=${ip}

${!byIp && dids.length ? `
; register so the distributor can send you inbound DID calls
[sipdist-reg]
type=registration
outbound_auth=sipdist-auth
server_uri=sip:${ip}:${sipPort}
client_uri=sip:p_${p.code}@${ip}:${sipPort}
contact_user=${user}
retry_interval=30
expiration=300
` : ''}
; extensions.conf — every call: dial our number ${dummy} with the caller-ID DID and the customer number
; in headers ${hdr.did} / ${hdr.nn} (digits, optional leading +; the DID must be one of the caller-ID DIDs
; on our trunk). Max ${p.channel_limit} calls at once. Any other number or a missing header is rejected.
[from-internal-sipdist]
exten => _X.,1,Set(SD_USE_DID=1234)   ; <- the DID to show as caller ID
 same => n,Dial(PJSIP/${dummy}@sipdist,60,b(sipdist-hdr^s^1(\${SD_USE_DID},\${EXTEN})))
 same => n,Hangup()

[sipdist-hdr]
exten => s,1,Set(PJSIP_HEADER(add,${hdr.did})=\${ARG1})
 same => n,Set(PJSIP_HEADER(add,${hdr.nn})=\${ARG2})
 same => n,Return()

; inbound calls from the distributor arrive here (callbacks to DIDs you used as X-DID${dids.length ? `, and your DIDs ${dids.map(clean).join(', ')}` : ''}):
; number = the caller's (customer) number, caller ID = the DID that was called; also in headers X-Number / X-DID
[from-sipdist]
exten => _X.,1,NoOp(inbound call from \${EXTEN} to DID \${CALLERID(num)})
 same => n,Goto(from-pstn,\${EXTEN},1)   ; change to your inbound context
`;
  const chanSip =
`; ===== chan_sip (sip.conf / ViciDial carrier) =====
[sipdist]
type=friend
host=${ip}
port=${sipPort}
${byIp ? '' : `username=${user}\nsecret=${pass}\nfromuser=${user}\n`}context=from-sipdist
disallow=all
allow=ulaw
allow=alaw
insecure=port,invite
qualify=yes
nat=force_rport,comedia

; dialplan — every call: dial ${dummy} with the caller-ID DID + customer number in headers
exten => _X.,1,SIPAddHeader(${hdr.did}: 1234)   ; <- the DID to show as caller ID
 same => n,SIPAddHeader(${hdr.nn}: \${EXTEN})
 same => n,Dial(SIP/${dummy}@sipdist,60)
 same => n,Hangup()
${!byIp && dids.length ? `
; [general] section of sip.conf — needed to receive inbound DID calls
register => p_${p.code}:${pass}:${user}@${ip}:${sipPort}
` : ''}`;
  return { pjsip: pj.replace(/\n{3,}/g, '\n\n'), chan_sip: chanSip };
}

module.exports = { renderTrunks, renderProcesses, renderDialplan, peerConfig, didParts, NAME_RE, SIP_CAUSE, DEFAULT_REJECT };
